In [81]:
import numpy as np

In [82]:
students_df = pd.read_csv('Data File/StudentPerformanceFactors.csv')

In [83]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [84]:
students_df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [85]:
students_df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [86]:
students_df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [109]:
students_df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [108]:
for col in ['Teacher_Quality', 'Parental_Education_Level', 'Distance_from_Home']:
    students_df[col].fillna(students_df[col].mode()[0], inplace=True)

students_df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [110]:
cat_cols = students_df.select_dtypes(include='object').columns

for col in cat_cols:
    print(students_df[col].value_counts())
    print("\n")

In [106]:
ordinal_cols = [
    'Parental_Involvement',
    'Access_to_Resources',
    'Motivation_Level',
    'Family_Income',
    'Teacher_Quality',
    'Parental_Education_Level',
    'Distance_from_Home'
]

nominal_cols = [
    'Extracurricular_Activities',
    'Internet_Access',
    'School_Type',
    'Peer_Influence',
    'Learning_Disabilities',
    'Gender'
]

In [111]:
for col in ordinal_cols:
    print(col, students_df[col].unique())

Parental_Involvement [1 2 3]
Access_to_Resources [3 2 1]
Motivation_Level [1 2 3]
Family_Income [1 2 3]
Teacher_Quality [2 3 1]
Parental_Education_Level [1 2 3]
Distance_from_Home [1 2 3]

In [92]:
mapping = {
    'Low': 1,
    'Medium': 2,
    'High': 3
}

for col in [
    'Parental_Involvement',
    'Access_to_Resources',
    'Motivation_Level',
    'Family_Income',
    'Teacher_Quality'
]:
    students_df[col] = students_df[col].map(mapping)

In [93]:
students_df['Distance_from_Home'] = students_df['Distance_from_Home'].map({
    'Near': 1,
    'Moderate': 2,
    'Far': 3
})

In [94]:
students_df['Parental_Education_Level'] = students_df['Parental_Education_Level'].map({
    'High School': 1,
    'College': 2,
    'Postgraduate': 3
})

In [112]:
for col in nominal_cols:
    print(col, students_df[col].unique())

Extracurricular_Activities [0 1]
Internet_Access [1 0]
School_Type [0 1]
Peer_Influence [2 0 1]
Learning_Disabilities [0 1]
Gender [1 0]

In [96]:
binary_map = {
    'Yes': 1,
    'No': 0
}

students_df['Internet_Access'] = students_df['Internet_Access'].map(binary_map)
students_df['Extracurricular_Activities'] = students_df['Extracurricular_Activities'].map(binary_map)
students_df['Learning_Disabilities'] = students_df['Learning_Disabilities'].map(binary_map)

In [97]:
students_df['Gender'] = students_df['Gender'].map({"Male" : 1, "Female" : 0})

In [98]:
students_df['School_Type'] = students_df['School_Type'].map({
    'Public': 0,
    'Private': 1
})

In [99]:
students_df['Peer_Influence'] = students_df['Peer_Influence'].map({
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
})

In [114]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   int64
 3   Access_to_Resources         6607 non-null   int64
 4   Extracurricular_Activities  6607 non-null   int64
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   int64
 8   Internet_Access             6607 non-null   int64
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   int64
 11  Teacher_Quality             6607 non-null   int64
 12  School_Type                 6607 non-null   int64
 13  Peer_Influence              6607 non-null   int64
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   int64
 16  Parental_Education_Level    6607 non-null   int64
 17  Distance_from_Home          6607 non-null   int64
 18  Gender                      6607 non-null   int64
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(20)
memory usage: 1.0 MB

In [101]:
students_df['Parental_Education_Level'] = students_df['Parental_Education_Level'].astype(int)
students_df['Distance_from_Home'] = students_df['Distance_from_Home'].astype(int)

In [115]:
students_df.rename(columns={
    'Parental_Involvement': 'parental_involvement_id',
    'Access_to_Resources': 'access_resource_id',
    'Extracurricular_Activities': 'extracurricular_activity_id',
    'Motivation_Level': 'motivation_id',
    'Internet_Access': 'internet_access_id',
    'Family_Income': 'family_income_id',
    'Teacher_Quality': 'teacher_quality_id',
    'School_Type': 'school_type_id',
    'Peer_Influence': 'peer_influence_id',
    'Learning_Disabilities': 'learning_disability_id',
    'Parental_Education_Level': 'parental_education_id',
    'Distance_from_Home': 'distance_from_home_id',
    'Gender': 'gender_id'
}, inplace=True)

In [117]:
print(students_df.columns.tolist())

['Hours_Studied', 'Attendance', 'parental_involvement_id', 'access_resource_id', 'extracurricular_activity_id', 'Sleep_Hours', 'Previous_Scores', 'motivation_id', 'internet_access_id', 'Tutoring_Sessions', 'family_income_id', 'teacher_quality_id', 'school_type_id', 'peer_influence_id', 'Physical_Activity', 'learning_disability_id', 'parental_education_id', 'distance_from_home_id', 'gender_id', 'Exam_Score']

In [116]:
students_df.to_csv('students_cleaned_data.csv', index=False)